import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Ibanez MD39C 39 inch Cutaway Acoustic Guitar",
    rating: 4,
    price: 5800,
    categoryName: "guitar",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/ibanez-md39c-634955_m.jpg",
  },
  {
    _id: uuid(),
    title: "Mantic MG370c Acoustic Guitar - Concert Size",
    rating: 3,
    price: 6000,
    categoryName: "guitar",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/bk-439569_m.jpg",
  },
  {
    _id: uuid(),
    title: "Ortega RST5 Student Series 6 String Classical Guitar",
    rating: 5,
    price: 7000,
    categoryName: "guitar",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/bg2-685122_m.jpg",
  },
  {
    _id: uuid(),
    title: "Taylor Builder's Edition Grand Concert Acoustic",
    rating: 4,
    price: 6000,
    categoryName: "guitar",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/builders-edition-912ce-whb1-266802_m.jpg",
  },
  {
    _id: uuid(),
    title: "Mantic Series AG2c String Acoustic Guitar",
    rating: 4,
    price: 8500,
    categoryName: "guitar",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/x1-pro-6-421094l-677374_m.jpg",
  },
  {
    _id: uuid(),
    title: "Yamaha FX280 Spruce Acoustic-Electric Guitar",
    rating: 3,
    price: 10000,
    categoryName: "guitar",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/fx280-natural-668172_m.jpg",
  },
  {
    _id: uuid(),
    title: "Ibanez V50NJP Dreadnought Acoustic Pack",
    rating: 3,
    price: 9500,
    categoryName: "guitar",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/natural-329260_m.jpg",
  },
  {
    _id: uuid(),
    title: "Havana HV 522 5Pcs Acoustic Drum Set",
    rating: 2,
    price: 22000,
    categoryName: "drum",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/havana-acoustic-drum-hv-522-sdl763964503-1-b83474000xprogressive-148364_m.jpg",
  },
  {
    _id: uuid(),
    title: "Ludwig Accent Drive Acoustic Drum Kit",
    rating: 4,
    price: 25000,
    categoryName: "drum",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/accent1-369761_m.jpg",
  },
  {
    _id: uuid(),
    title: "Tama Club JAM Kit 4 Piece LJK48H4 AQB",
    rating: 4,
    price: 28000,
    categoryName: "drum",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/club-137464_m.jpg",
  },
  {
    _id: uuid(),
    title: "Tama Imperial Star 5 Piece Drum kit IE58H6",
    rating: 5,
    price: 25000,
    categoryName: "drum",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/cpm-674693_m.jpg",
  },
  {
    _id: uuid(),
    title: "Tama Rhythm Mate Drumkit RM50KH5",
    rating: 3,
    price: 21000,
    categoryName: "drum",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/hlb-1-828649_m.jpg",
  },
  {
    _id: uuid(),
    title: "Peace Drums X4 Series Acoustic Drum Kit",
    rating: 4,
    price: 27000,
    categoryName: "drum",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/dpx4-281751_m.jpg",
  },
  {
    _id: uuid(),
    title: "sE Electronics X1 A Large-diaphragm Microphone",
    rating: 4,
    price: 8000,
    categoryName: "studio-equipment",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/x1a-804507_m.jpg",
  },
  {
    _id: uuid(),
    title: "MixPad® MXP124FX - Compact, Analog Stereo Mixer",
    rating: 4,
    price: 19000,
    categoryName: "studio-equipment",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/mxp124fxheadon-173622_m.jpg",
  },
  {
    _id: uuid(),
    title: "Focusrite Scarlett Solo USB Audio Interface",
    rating: 3,
    price: 17000,
    categoryName: "studio-equipment",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/solos2-510411_m.jpg",
  },
  {
    _id: uuid(),
    title: "Havana MV1412F Violin with Ebony Pegs",
    rating: 5,
    price: 13000,
    categoryName: "traditional-equipment",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/cello-508542_m.jpg",
  },
  {
    _id: uuid(),
    title: "Havana M5210 Bb Trumpet - Gold Lacquer Finish",
    rating: 4,
    price: 27000,
    categoryName: "traditional-equipment",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/m5210-292199_m.jpg",
  },
  {
    _id: uuid(),
    title: "Jinbao Tenor Saxophone - JBTS100",
    rating: 4,
    price: 12000,
    categoryName: "traditional-equipment",
    src: "https://www.johnsmusic.in/uploads/johns-music/products/jbts100-621853_m.jpg",
  },
];
